# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.3.4
_src_path: gh:algorandfoundation/algokit-python-template
author_email: studyug@hotmail.com
author_name: Oliseh Genesis
contract_name: pouch_wise
deployment_language: python
preset_name: starter
project_name: pouch-wise-contracts

