# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.0.8
_src_path: gh:algorandfoundation/algokit-react-frontend-template
author_email: studyug@hotmail.com
author_name: Oliseh Genesis
preset_name: starter
project_name: pouch-wise-frontend

